/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Suresh' at '18/6/16 1:05 AM' with Gradle 2.6
 *
 * @author Suresh, @date 18/6/16 1:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
